#!/bin/sh

BASEDIR=`dirname $0`

LIBDIRS="$BASEDIR/lib"
CLASSPATH=
MAIN="org.kohsuke.youdebug.YouDebug"
OS=`uname -o 2>/dev/null`
if [ -z "$JAVA" ]; then
	JAVA=java
fi

for dir in $LIBDIRS; do
	for jar in $dir/*.jar; do
		if [ -n "$CLASSPATH" ]; then
			case "$OS" in
			[Cc]ygwin)	CLASSPATH="$CLASSPATH;$jar";;
			*)			CLASSPATH="$CLASSPATH:$jar";;
			esac
		else
			 CLASSPATH="$jar"
		fi
	done
done

"$JAVA" $JAVA_OPTS -cp $CLASSPATH $MAIN "$@"